#base
spring.application.name=Telemetry-collector-service
spring.main.banner-mode=OFF
server.port=8080

#kafka
collector.kafka.bootstrap-servers=localhost:9092
collector.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
collector.kafka.value-serializer=ru.yandex.practicum.collector.serialization.GeneralAvroSerializer
collector.kafka.sensorTopic=telemetry.sensors.v1;
collector.kafka.hubTopic=telemetry.hubs.v1;
