#kafka
kafka:
  snapshot-consumer-group-id: analyzer-snapshot-group
  snapshot-consumer-topic: telemetry.snapshots.v1
  snapshot-consumer-key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  snapshot-consumer-value-deserializer: ru.yandex.practicum.collector.serialization.deserializer.SnapshotDeserializer
  snapshot-consumer-enable-auto-commit-config: "false"
  snapshot-consumer-auto-offset-reset-config: earliest
  snapshot-consumer-max-poll-records-config: 100

  hub-event-consumer-group-id: analyzer-hub-event-group
  hub-event-consumer-topic: telemetry.hubs.v1
  hub-event-consumer-key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  hub-event-consumer-value-deserializer: ru.yandex.practicum.collector.serialization.deserializer.HubEventDeserializer
  hub-event-consumer-enable-auto-commit-config: "false"
  hub-event-consumer-auto-offset-reset-config: earliest
  hub-event-consumer-max-poll-records-config: 10


# gRPC
grpc:
  client:
    hub-router:
      address: static://127.0.0.1:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

# BD
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: dbuser
    password: "12345"
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
    open-in-view: false

  # SQL
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql