#base
spring.application.name=Telemetry-aggregator-service
spring.main.banner-mode=OFF
logging.level.ru.yandex.practicum.aggregator=DEBUG

#kafka
aggregator.kafka.bootstrap-servers=localhost:9092
aggregator.kafka.group=group.id
aggregator.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
aggregator.kafka.value-serializer=ru.yandex.practicum.collector.serialization.GeneralAvroSerializer
aggregator.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
aggregator.kafka.value-deserializer=ru.yandex.practicum.collector.serialization.deserializer.SensorEventDeserializer
aggregator.kafka.sensorTopic=telemetry.sensors.v1
aggregator.kafka.snapshotTopic=telemetry.snapshots.v1
aggregator.kafka.maxPoll=100

