spring:
  main:
    banner-mode: off
    log-startup-info: false

logging:
  level:
    ru.yandex.practicum.telemetry: ERROR
    org:
      springframework: ERROR
      apache.kafka: WARN

kafka:
  bootstrap-servers: "localhost:9092"
